name: boomboxswap
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - nodejs=18
  # Cache mémoire BoomboxCache utilisé à la place de Redis
  # pour éviter les dépendances externes sur Windows
  - pip:
      - fastapi==0.104.1
      - uvicorn[standard]==0.24.0
      - web3==6.11.3
      - python-dotenv==1.0.0
      - pydantic==2.5.0
      - httpx==0.25.2
      - aiohttp==3.9.1
      - asyncio-mqtt==0.16.1
      - python-multipart==0.0.6
      - jinja2==3.1.2
      - python-jose[cryptography]==3.3.0
      - passlib[bcrypt]==1.7.4
      - python-decouple==3.8
      - requests==2.31.0
      - websockets==12.0
      - aiofiles==23.2.1
      - psutil==5.9.6
      - pytest==7.4.3
      - pytest-asyncio==0.21.1
      - black==23.11.0
      - flake8==6.1.0
      - mypy==1.7.1
